update CI
MirahezeBots/sopel-channelmgnt pull request #13
Opened 2020-12-30 23:25 UTC by RhinosF1

2020-12-30 23:26 UTC, MacFan4000 commented
I was doing it in my PR

2020-12-30 23:29 UTC, RhinosF1 commented
so I can fix what fails

2020-12-31 10:55 UTC, RhinosF1 commented
@MacFan4000: can you update the tests submodule to dev?

2020-12-31 12:14 UTC, MacFan4000 requested changes

2020-12-31 12:14 UTC, MacFan4000 commented on .github/workflows/workflow.yml
> +          flake8 . --max-line-length 265 --exclude=*/__init__.py
Excluding __init__.py means we are excluding the plug-in code

2020-12-31 12:23 UTC, MacFan4000 commented
> @MacFan4000: can you update the tests submodule to dev?

done

2020-12-31 15:53 UTC, MacFan4000 approved these changes

2020-12-31 15:56 UTC, merged